version: '3.3'

services:
  solr:
    container_name: solr
    image: solr:$SOLR_VERSION
    volumes:
      - type: volume
        source: solr
        target: /var/solr
    ports:
      - "8983:8983"
    networks:
      - fourplusone
    command:
      - solr-precreate
      - gettingstarted
  
    # restart: always

  couchdb:
    container_name: couchdb
    image: couchdb:$COUCHDB_VERSION
    volumes:
      - type: volume
        source: couchdb
        target: /opt/couchdb/data
    ports:
      - "5984:5984"
    networks:
      - fourplusone
    environment:
      COUCHDB_USER: $COUCHDB_USER
      COUCHDB_PASSWORD: $COUCHDB_PASSWORD
    # restart: always

  web_service:
    build: ../web_service
    container_name: web_service
    ports:
      - "5000:5000"
    networks:
      - fourplusone
    # restart: always

  api:
    build: ../api
    container_name: api
    ports:
      - "4000:4000"
    networks:
      - fourplusone
    # restart: always

networks:
  fourplusone:
    driver: bridge

volumes:
  solr:
    driver: local
  couchdb:
    driver: local